name: Enrich Issue Descriptions

on:
  schedule:
    # Run daily at 7am Madrid time (UTC+2)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  enrich-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Find issues with improve-description label
        id: find-issues
        run: |
          ISSUES=$(gh issue list --label "improve-description" --json number,title,body,url -R ${{ github.repository }} | jq -c '.')
          echo "ISSUES=$ISSUES" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Enrich issue descriptions
        if: env.ISSUES != '[]' && env.ISSUES != ''
        run: |
          ISSUES_JSON='${{ env.ISSUES }}'
          echo "$ISSUES_JSON" | jq -c '.[]' | while read -r issue; do
            ISSUE_NUMBER=$(echo "$issue" | jq -r '.number')
            ISSUE_TITLE=$(echo "$issue" | jq -r '.title')
            ISSUE_BODY=$(echo "$issue" | jq -r '.body')
            
            echo "Processing issue #$ISSUE_NUMBER: $ISSUE_TITLE"
            
            # Prepare prompt for Claude
            PROMPT="You are a helpful assistant that improves github issue descriptions to make them more clear, structured, and actionable. Please enrich the following issue description without changing its original meaning or intent. Add the following sections to the new description: Overview, Current Behavior, Requested Change, Context files or subproject and Implementation Considerations. Consider these optional sections too: Expected Benefits and Additional Information. Here is the current description:\n\n$ISSUE_BODY\n\nProvide only the improved description without any explanations."
            
            # Call Claude API
            ENRICHED_DESCRIPTION=$(curl -s https://api.anthropic.com/v1/messages \
              -H "Content-Type: application/json" \
              -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
              -H "anthropic-version: 2023-06-01" \
              -d '{
                "model": "claude-3-7-sonnet-20250219",
                "max_tokens": 4000,
                "messages": [
                  {
                    "role": "user",
                    "content": "'"$PROMPT"'"
                  }
                ]
              }' | jq -r '.content[0].text')
            
            # Update the issue description
            gh issue edit $ISSUE_NUMBER --body "$ENRICHED_DESCRIPTION" -R ${{ github.repository }}
            
            # Remove the improve-description label
            gh issue edit $ISSUE_NUMBER --remove-label "improve-description" -R ${{ github.repository }}
            
            echo "Updated issue #$ISSUE_NUMBER description and removed label"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}